name: Deploy FastAPI to Lambda

on:
  push:
    branches:
      - master
    paths:
      - api-web-scraper/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r api-web-scraper/requirements.txt

    - name: Build and package
      run: |
        mkdir package
        cp -r api-web-scraper/app/* package/
        cp api-web-scraper/app/main.py package/
        cd package
        zip -r ../deployment.zip .
        cd ..

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Lambda
      run: |
        aws cloudformation package \
          --template-file api-web-scraper/template.yaml \
          --s3-bucket ${{ secrets.AWS_BUCKET_NAME }} \
          --output-template-file packaged.yaml

        aws cloudformation deploy \
          --template-file packaged.yaml \
          --stack-name fastapi-web-scraperlambda-stack \
          --capabilities CAPABILITY_IAM
